### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by tammersaleh** [superorbital/cludo#45]
Depends on #60 

Does this mean we need our own https://helm.superorbital.io repo?  How hard is that?  Can we point that at S3 or something?  Maybe use Github artifacts?

Need to register this chart with https://artifacthub.io/

Whenever we create a new Github release (See #60), we should also release a new version of the chart.

Update the documentation adding a section about installing to K8s using the chart.

**Comment by spkane** [comment]
@tammersaleh To answer some of your questions here:

For starters people can simply pull down this repo and use `helm install cludod ./k8s/helm/cludod/` against the unpacked files.

We can create a helm repo in gtihub reasonably easily with something like this (which uses a Github repo, Pages, Actions and Releases)
https://harness.io/blog/helm-chart-repo/

This is a link to information on adding a Helm repo to ArtifactHub.
https://artifacthub.io/docs/topics/repositories/#helm-charts-repositories



We should be able to create a DNS CNAME to point to the Github pages endpoint, easy enough, if we want to.

**Comment by spkane** [comment]
We now have a helm repo at:
https://helm.superorbital.io/

That is maintained here:
https://github.com/superorbital/helm-charts

**Comment by spkane** [comment]
ArtifactHub:
https://artifacthub.io/packages/search?repo=superorbital

**Comment by spkane** [comment]
done (for now)
