### ISSUE TITLE
Authenticate against Github public keys (either enterprise or public)

### ISSUE THREAD

**Issue by jmcshane** [superorbital/cludo#47]
Github provides a public endpoint to list the public keys for a user. Rather than storing the public keys directly, we could use Github to retrieve the public keys.

The cludo client config would need a auth type/username section to tell the server to use this endpoint.

**Comment by tammersaleh** [comment]
oh, that's a _very_ cool idea

**Comment by spkane** [comment]
We had GHE (Github Enterprise) at New Relic and we used this endpoint as the source of truth for user public keys in some cases. It worked very well for that.

**Comment by jmcshane** [comment]
I want to pursue this next now that we have refactored the root config. Any concern with me doing this next?

**Comment by tammersaleh** [comment]
by all means

**Comment by jmcshane** [comment]
At this time, we are going to force both the user and the server to specify the github username. Then, the server config for the user will allow specifying either an inline SSH key or a URL. The URL will be parsed and appropriate action will be taken based on the result from that url.

I will be adding the username as a base64 encoded string in the header. Currently, the header is encrypted_text:signature, but I will append :username into that header string.

**Comment by tammersaleh** [comment]
I think that was our first idea, but in the end we decided to:
- not specify github user in the client config
- specify github user in the server config
- have the server loop over all configured github names, downloading the public keys for each auth request
- punt on caching until we "need" it

**Comment by spkane** [comment]
Just reading over this and thinking that, since these public keys are typically pretty stable, the server could pull down the pub keys from github when it first encounters a user and then store them, and then only check github again when that user tries to authenticate with a secret key that the server does not already have a matching pub key for.

**Comment by tammersaleh** [comment]
Yeah, I think that's a good caching strategy, but in the interest of "getting it done", I'd still like to punt on even caching that's that simple until we need it.

**Comment by spkane** [comment]
> * have the server loop over all configured github names, downloading the public keys for each auth request

Is this really a good idea, since it will happen before any client auth and on every single request? It feels ripe for abuse, both DoS attacks against `cludod` and rate limiting from Github.

**Comment by spkane** [comment]
> * have the server loop over all configured github names, downloading the public keys for each auth request

@tammersaleh Is this really a good idea, since it will happen before any client auth and on every single request? It feels ripe for abuse, both DoS attacks against `cludod` and rate limiting from Github.

**Comment by tammersaleh** [comment]
> Is this really a good idea

No, but it's a good idea for now.  We're not confident Cludo will get any usage, so there's no point in optimizing for larger teams using it more frequently.

But it's clear that this is something that'll have to be fixed as soon as any real usage happens, so I've created #92 so we don't forget.

I suppose a good addition to this issue, which will make it both more efficient _and_ more correct is to first loop through all registered public keys before then looping over all users with github identities configured.  I think it's fine adding that bit to the scope.
