### ISSUE TITLE
Manage PR container image releases

### ISSUE THREAD

**Issue by spkane** [superorbital/cludo#65]
At the moment we are pushing PR releases to Docker Hub. We should come up with a way to manage these.

Either delete them after so many days or push them to an internal registry (and really still delete them after so many days)

**Comment by tammersaleh** [comment]
What about having an action delete them when the PR closes?

**Comment by spkane** [comment]
> What about having an action delete them when the PR closes?

That might work. We'll just need to see if I can easily trigger on that event, or something closely related to that.

**Comment by spkane** [comment]
done. Closing a PR should now delete all the images that were build via the Github Actions
