### ISSUE TITLE
`cludod` should look for `cludod.yaml` by default instead of `cludo.yaml`

### ISSUE THREAD

**Issue by spkane** [superorbital/cludo#77]
* Current Default Behaviour

```sh
$ builds/darwin_amd64_cludod --port=999 --scheme=http --host=0.0.0.0
2022/01/11 11:22:06 error: Config File "cludo" Not Found in "[/etc/cludod /Users/spkane/.cludod /Users/spkane/.config/cludod /Users/spkane/dev/superorbital/cludo]"
2022/01/11 11:22:06 Serving cludod at http://[::]:999
^C2022/01/11 11:22:22 Shutting down...
2022/01/11 11:22:22 Stopped serving cludod at http://[::]:999
```

* A workaround

```sh
builds/darwin_amd64_cludod --config=/etc/cludod/cludod.yaml --port=999 --scheme=http --host=0.0.0.0
2022/01/11 11:22:51 Serving cludod at http://[::]:999
```

**Comment by tammersaleh** [comment]
Do we think this feature of auto-discovering config file locations is worth the complexity?  what if we just required the `-f` flag instead?

**Comment by spkane** [comment]
> Do we think this feature of auto-discovering config file locations is worth the complexity? what if we just required the `-f` flag instead?

It's a valid question, but I'm not sure that it really relates to the issue at hand. The library we use gives us this config search for free and we have a `--config` options already.

My point here was that `cludod` appears to look for `cludo.yaml` instead of `cludod.yaml`.

**Comment by tammersaleh** [comment]
Oh, I misunderstood the issue - thanks!

**Comment by spkane** [comment]
It turns out the issue was a little diffirent then what I reported here. PR #85 explains this a bit and fixes it.
