### ISSUE TITLE
Remove the ability to provide the SSH passphrase in the config or via CLI args

### ISSUE THREAD

**Issue by spkane** [superorbital/cludo#80]
Putting the passphrase in the config doesn't feel like it is every going to be a good idea.

Either:
- use an SSH agent
- prompt for it
- use a passphrase-less key
- or *maybe* read it from an env var (still not secure, but at least a middle ground)

**Comment by tammersaleh** [comment]
100% agreed

**Comment by tammersaleh** [comment]
> or maybe read it from an env var (still not secure, but at least a middle ground)

Let's not do this yes.

**Comment by spkane** [comment]
@tammersaleh It will mean that there is NO WAY to automate using the `cludo` CLI with a passphrased SSH key, since someone will have to type in the passphrase for either `cludo` or the SSH agent. I am fine with this, but want to point it out, as an intentional design decision, if we are going to do this.

**Comment by tammersaleh** [comment]
Yeah, I'm also fine with this for now.  We may decide to support passphrases later, but 🤷
