### ISSUE TITLE
Support iterating over multiple SSH keys and determining the correct one to use in all scenarios

### ISSUE THREAD

**Issue by spkane** [superorbital/cludo#81]
As mentioned in #52 , now that we have added a list of SSH keys into the client config we will need to add logic to iterate over these and choose the appropriate key to use in the supported situations.

For example in: `NewDefaultSigner()`

**Comment by spkane** [comment]
I agree that this seems like the right approach. How difficult it ends up being will simply depend on the current implementation of the code.

As we try each key, we will at least need to:
* Unlock the key, if passphrase protected
* Determine if it is an RSA key, since that is all we support :(
* Jump through the normal logic and then send it to the server, and handle an unknown key error, to trigger trying the next one.

**Comment by tammersaleh** [comment]
Agreed.
